# SPDX-License-Identifier: 0BSD
# FEKernel 引导菜单配置（Limine 12.x 格式）
timeout: 3
interface_branding: FEKernel Bootloader
verbose: no

/FEKernel
    protocol: limine
    path: boot():/boot/kernel.elf
    # 用户态服务以模块形式随内核一起加载，由内核解析后交给 init
    # module_path: boot():/boot/servers/init.elf

/FEKernel (串口调试)
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: debug verbose
